spring:
  application:
    name: tournament

  data:
    mongodb:
      uri: mongodb+srv://sreemanvk:Sree2001@cluster0.pvohmlz.mongodb.net/?appName=Cluster0
      database: tournament

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"


server:
  port: 7073

wallet:
  id: 67d0194aa6f0ff431202ca64

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
    fetch-registry: true
    register-with-eureka: true
