spring:
  application:
    name: room-creation

  data:
    mongodb:
      uri: mongodb+srv://sreemanvk:Sree2001@cluster0.pvohmlz.mongodb.net/game_room?appName=Cluster0
      database: game_room

logging:
  file:
    name: logs/room-creation.log
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}] [%thread] %logger{36} - %msg%n"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: ${PORT:8080}

wallet:
  id: your_actual_wallet_id_here

