spring:
  application:
    name: room-creation

  redis:
    url: ${REDIS_URL}

  data:
    mongodb:
      uri: mongodb+srv://sreemanvk:Msg2709@cluster0.pvohmlz.mongodb.net/game_room?appName=Cluster0

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"


eureka:
  client:
    service-url:
      defaultZone: https://rummy-eureka-v1.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: rummy-room-creation.onrender.com # Use the actual Render URL for this service
    instance-id: ${spring.application.name}:${random.value}
    non-secure-port: ${PORT}
    prefer-ip-address: false

server:
  port: ${PORT:8080}

wallet:
  id: ${WALLET_ID}

