spring:
  application:
    name: wallet

  data:
    mongodb:
      uri: mongodb+srv://sreemanvk:Sree2001@cluster0.pvohmlz.mongodb.net/?appName=Cluster0
      database: rummy_wallet


logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"


server:
  port: 7077

eureka:
  client:
    service-url:
      defaultZone: https://rummy-eureka-v1-35lo.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: rummy-wallet-v1-6b5v.onrender.com
    prefer-ip-address: false