spring:
  application:
    name: game-engine

  data:
    mongodb:
      uri: mongodb+srv://sreemanvk:Sree2001@cluster0.pvohmlz.mongodb.net/?appName=Cluster0
      database: game_room

logging:
  file:
    name: logs/game-engine.log
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}] [%thread] %logger{36} - %msg%n"

server:
  port: 7072
  address: 0.0.0.0

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
#  instance:
#    # This will change how it appears in the Eureka Dashboard
#    instance-id: ${spring.application.name}:${random.value}
#    hostname: rummy-gameengine-v1-c9pv.onrender.com
#    # This ensures it uses the IP/Internal host for communication
#    prefer-ip-address: true
